#!/bin/zsh
# set -x

# exec &>> /tmp/test

backup_log=/home/ross/.backup_logs
folders=('/etc' '/home/ross/Dropbox' '/home/ross/music' '/home/ross/pictures' '/home/ross/programming' '/home/ross/.dotphiles' $backup_log)
# excludes="'/home/ross/.cache','/home/ross/downloads','/home/ross/.mozilla','/home/ross/.hoogle',''"

# rsync_opts="-az --delete -e ssh"
# -a = rlptgoD
# -r recursive
# -l copy links as links
# -p
# -z compress
# -u update (skip newer files)
# -v verbose
# -t preserve times
rsync_opts="-rlzuv --omit-dir-times --delete"
#rsync_opts="-avz -e ssh"
remote_base="/run/media/ross/btrfs700/backup"


## create a file to record the time to of the backup
touch $backup_log/$(date +%y%m%d-%H%M)
for f in $folders; do
    echo "====================="
    echo $f
    echo "====================="
    rsync ${=rsync_opts} $f/ $remote_base$f/
done