#!/bin/sh

power=$(cat '/sys/class/power_supply/BAT1/capacity')
status=$(cat '/sys/class/power_supply/BAT1/status')

if [[ $status == "Full" ]]; then
icon_name="/usr/share/icons/elementary/status/48/battery-ac-adapter.svg"


elif [[ $status == "Charging" ]]; then
icon_name="/usr/share/icons/elementary/status/48/battery-full-charging.svg"
if (( $power < 95 )); then
    icon_name="/usr/share/icons/elementary/status/48/battery-good-charging.svg"
fi
if (( $power < 15 )); then
   icon_name="/usr/share/icons/elementary/status/48/battery-caution-charging.svg"
fi
if (( $power < 5 )); then
   icon_name="/usr/share/icons/elementary/status/48/battery-empty-charging.svg"
fi


else
icon_name="/usr/share/icons/elementary/status/48/battery-full.svg"

if (( $power < 95 )); then
    icon_name="/usr/share/icons/elementary/status/48/battery-good.svg"
fi
if (( $power < 15 )); then
   icon_name="/usr/share/icons/elementary/status/48/battery-caution.svg"
fi
if (( $power < 5 )); then
   icon_name="/usr/share/icons/elementary/status/48/battery-empty.svg"
fi

fi

# echo $icon_name
# echo $power

notify-send "$power" -i $icon_name
# notify-send " "  -h int:value:$power -h string:synchronous:battery
