#!/bin/zsh

if [[ $HOST == "nyx" ]]; then
power=$(cat '/sys/class/power_supply/BAT1/capacity')
charging_status=$(cat '/sys/class/power_supply/BAT1/status')
elif [[ $HOST == "aion" ]]; then
power=$(cat '/sys/class/power_supply/BAT0/capacity')
charging_status=$(cat '/sys/class/power_supply/BAT0/status')
fi

if [[ $charging_status == "Full" ]]; then
icon_name="/usr/share/icons/elementary/status/48/battery-ac-adapter.svg"


elif [[ $charging_status == "Charging" ]]; then
icon_name="/usr/share/icons/elementary/status/48/battery-full-charging.svg"
if (( $power < 95 )); then
    icon_name="/usr/share/icons/elementary/status/48/battery-good-charging.svg"
fi
if (( $power < 15 )); then
   icon_name="/usr/share/icons/elementary/status/48/battery-caution-charging.svg"
fi
if (( $power < 5 )); then
   icon_name="/usr/share/icons/elementary/status/48/battery-empty-charging.svg"
fi


else
icon_name="/usr/share/icons/elementary/status/48/battery-full.svg"

if (( $power < 95 )); then
    icon_name="/usr/share/icons/elementary/status/48/battery-good.svg"
fi
if (( $power < 15 )); then
   icon_name="/usr/share/icons/elementary/status/48/battery-caution.svg"
fi
if (( $power < 5 )); then
   icon_name="/usr/share/icons/elementary/status/48/battery-empty.svg"
fi

fi

case $1 in
"help")
  echo "Usage: icon|level|show"
  ;;
"icon")
  echo $icon_name
  ;;
"level")
  echo $power
  ;;
"show"|*)
  notify-send "$power" -i $icon_name
  ;;
esac

exit 1
