#!/bin/zsh

zmodload zsh/mathfunc

ratioUP=1.5
ratioDOWN=0.66

show() {
  icon_name="/usr/share/notify-osd/icons/hicolor/scalable/status/display-brightness-symbolic.svg"
  # level=$( printf "%.0f" `light -G` )
  level=`light -G`
  echo $level
  (( level = log( 1 + level) / log( 101 ) * 100 ))
  echo $level
  notify-send " " -i $icon_name -h int:value:$level -h string:synchronous:brightness
}

case $1 in
"help")
  echo "Usage: up|down|level"
  ;;
"up")
  sudo light -T $ratioUP
  show
  ;;
"down")
  sudo light -T $ratioDOWN
  show
  ;;
"level")
  light -G
  ;;
"show")
  show
  ;;
*)
  echo "Usage: up|down|level"
  echo "Brightness: " `$0 level`
  ;;
esac

exit 1
