#!/bin/sh

completion='compctl -k "(help bash-completion ssh mount unmount permissions)" como'

case $1 in
"help")
	echo "Available options: help; ssh; mount; unmount; bash-completion"
	;;

"bash-completion")
	echo "$completion"
	;;

"mount")
    mkdir -p /media/como/{rosso,research,tutsols}

	sshfs rosso@como:/users/pmgrad/rosso /media/como/rosso

	sshfs rosso@como:/users/pmstaff/carberry/rome/research /media/como/research

	sshfs rosso@como:/users/misc/tutsols /media/como/tutsols

	#sshfs rosso@como:/users/misc/teaching/JM/MATH1001/ /media/como/1001
	#sshfs rosso@como:/users/pmstaff/carberry/teaching/SM/MATH3968 /media/como/3968
	#sshfs rosso@como:/users/misc/httpd/htdocs/u/UG/SM/MATH3968/r/ /media/como/3968wwwdir
	#sshfs rosso@como:/users/misc/teaching/HM/MATH4303/ /media/como/4303
	#sshfs rosso@como:/users/misc/httpd/htdocs/u/UG/HM/MATH4303/r/ /media/como/4303wwwdir
	;;

"unmount")
	for f in /media/como/*; do fusermount -u -z $f; done
	;;

"permissions")
	ssh -YC rosso@como << 'ENDSSH'
	#commands to run on remote host
	cd /users/pmgrad/rosso/MATH3968
	fix-my-teaching
	cd /users/pmgrad/rosso/MATH4303
	fix-my-teaching
ENDSSH
	;;

"ssh" | *)
	ssh -YC rosso@como
	;;
esac
