#!/bin/sh

case $1 in
"help")
	echo "Available options: help; ssh; mount; unmount"
	;;
	
"mount")
	sshfs rosso@como:/users/pmstaff/carberry/teaching/SM/MATH3968 /home/ross/mnt/usyd/3968
	sshfs rosso@como:/users/pmstaff/carberry/rome/research /home/ross/mnt/usyd/research
	sshfs rosso@como:/users/pmgrad/rosso /home/ross/mnt/usyd/rosso
	sshfs rosso@como:/users/misc/httpd/htdocs/u/UG/SM/MATH3968/r/ /home/ross/mnt/usyd/3968wwwdir
	sshfs rosso@como:/users/misc/teaching/JM/MATH1011/ /home/ross/mnt/usyd/1011
    sshfs rosso@como:/users/misc/httpd/htdocs/u/UG/JM/MATH1011/ /home/ross/mnt/usyd/1011webdir
	sshfs rosso@como:/users/misc/tutsols /home/ross/mnt/usyd/tutsols
	sshfs rosso@como:/users/misc/teaching/HM/MATH4303/ /home/ross/mnt/usyd/4303
	#sshfs rosso@como:/users/misc/httpd/htdocs/u/UG/HM/MATH4303/r/ /home/ross/mnt/usyd/4303wwwdir
	#sshfs rosso@como:/ /home/ross/como/root
	;;
	
"unmount")
	for f in /home/ross/mnt/usyd/*; do fusermount -u -z $f; done
	;;
	
"permissions")
	ssh -c arcfour,blowfish-cbc -YC rosso@como << 'ENDSSH'
	#commands to run on remote host
	cd /users/pmgrad/rosso/MATH3968
	fix-my-teaching
	cd /users/pmgrad/rosso/MATH4303
	fix-my-teaching
ENDSSH
	;;
"ssh" | *)
	ssh -c arcfour,blowfish-cbc -YC rosso@como
	;;
esac
