#!/bin/sh

completion='compctl -k "(help bash-completion ssh mount mount-remote unmount permissions)" dora'

case $1 in
"help")
	echo "Available options: help; ssh; mount; unmount; bash-completion"
	;;

"bash-completion")
	echo "$completion"
	;;

"mount")
    mkdir -p /media/dora/{rosso,research,tutsols}
    #mkdir -p /media/dora/{3968,3968wwwdir}
    mkdir -p /media/dora/{2916,2916wwwdir}
    mkdir -p /media/dora/{1002,1002wwwdir}

	sshfs rosso@dora:/users/pmgrad/rosso /media/dora/rosso
	sshfs rosso@dora:/users/pmstaff/carberry/rome/research /media/dora/research
	sshfs rosso@dora:/users/misc/tutsols /media/dora/tutsols

	#sshfs carberry@dora:/users/misc/teaching/JM/MATH1001/ /media/dora/1011
	#sshfs rosso@dora:/users/pmstaff/carberry/teaching/SM/MATH3968 /media/dora/3968
	#sshfs rosso@dora:/users/misc/httpd/htdocs/u/UG/SM/MATH3968/r/ /media/dora/3968wwwdir
	#sshfs rosso@dora:/users/misc/teaching/HM/MATH4303/ /media/dora/4303
	#sshfs rosso@dora:/users/misc/httpd/htdocs/u/UG/HM/MATH4303/r/ /media/dora/4303wwwdir
	
	sshfs carberry@dora:/users/misc/teaching/JM/MATH1002/ /media/dora/1002
	sshfs carberry@dora:/users/misc/httpd/htdocs/u/UG/JM/MATH1002/r/ /media/dora/1002wwwdir
	sshfs carberry@dora:/users/misc/teaching/IM/MATH2916/ /media/dora/2916
	sshfs carberry@dora:/users/misc/httpd/htdocs/u/UG/IM/MATH2916/r/ /media/dora/2916wwwdir
	;;

"mount-remote")
    mkdir -p /media/dora/{rosso,research,tutsols}
    mkdir -p /media/dora/{3968,3968wwwdir}
    mkdir -p /media/dora/{1011,1011wwwdir}

	sshfs rosso@maths.usyd.edu.au:/users/misc/teaching/JM/MATH1011/ /media/dora/1011
	sshfs rosso@maths.usyd.edu.au:/users/misc/httpd/htdocs/u/UG/JM/MATH1011/r/ /media/dora/1011wwwdir
	;;

"unmount")
	for f in /media/dora/*; do fusermount -u -z $f; done
	;;

"permissions")
	ssh -YC rosso@dora << 'ENDSSH'
	#commands to run on remote host
	cd /users/pmgrad/rosso/MATH3968
	fix-my-teaching
	cd /users/pmgrad/rosso/MATH4303
	fix-my-teaching
ENDSSH
	;;

"ssh" | *)
	ssh -YC rosso@dora
	;;
esac
