#!/bin/zsh

completion='compctl -k "(help bash-completion ssh mount unmount mount-backup unmount-backup vnc)" eris'


case $1 in
"help")
	echo "Available options:"
	echo "=> help				Shows this"
	echo "=> [ssh] [cmd]			Connects via ssh"
	echo "=> vnc				Opens a vnc session"
	echo "=> mount			Mount the shared folders"
	echo "=> unmount			Unmount the shared folders"
	echo "=> mount-backup			Mount the backup folder"
	echo "=> unmount-backup			Unmount the backup folder"
	;;

"bash-completion")
	echo "$completion"
	;;

"mount")
    mkdir -p /media/eris/seagate2
	sshfs -o idmap=user -o uid=$(id -u) -o gid=$(id -g) eris:/media/seagate2 /media/eris/seagate2

    mkdir -p /media/eris/eris
	sshfs -o idmap=user -o uid=$(id -u) -o gid=$(id -g) eris:/media/btrfs3-new/stuff /media/eris/eris
	;;

"unmount")
	shares=(seagate2 eris)
	for f in $shares; do fusermount -u /media/eris/$f; done
	;;

"mount-backup")
	mkdir -p /media/eris/backup
	sshfs -o idmap=user -o uid=$(id -u) -o gid=$(id -g) ross@eris:/media/btrfs3-new/backups/nyx /media/eris/backup
	;;

"unmount-backup")
	shares=(backup)
	for f in $shares; do fusermount -u /media/eris/$f; done
	rmdir /media/eris/backup
	;;


"vnc")
	ssh -N -p 443 -L 5900:localhost:5900 ssh.rossogilvie.id.au &
	vncviewer -encodings "copyrect tight zrle hextile zlib corre rre raw" localhost
	;;

"ssh")
	shift 1
	cmd=$*
	ssh eris $cmd && /home/ross/.scripts/fix-mouse
	;;

*)
	ssh eris && /home/ross/.scripts/fix-mouse
	;;

esac
