#!/bin/sh
/usr/bin/pactl load-module module-null-sink sink_name=icecast
/usr/bin/gst-launch-0.10 pulsesrc device=icecast.monitor ! audioconvert ! lamemp3enc target=1 bitrate=128 cbr=true ! shout2send ip=127.0.0.1 port=8000 password=fishyfishy mount=mystream.mp3
