#!/bin/sh
#
# This script toggles the extended monitor outputs if something is connected
#

export HOME=/home/ross
export DISPLAY=:0
export XAUTHORITY=/home/ross/.Xauthority

completion='compctl -k "(help bash-completion setup braces brackets greek)" keyboard'

# By default show the notification.
# Don't show it if this parameter is hidden
notify=$2

case $1 in
"setup"|"normal")
    numlockx on
		xmodmap $HOME/.xmodmap_standard
    xmodmap $HOME/.xmodmap_braces
    if [[ $notify != 'hidden' ]] # not empty
		then
		notify-send -i /usr/share/icons/gnome/48x48/devices/keyboard.png "Keyboard set up in normal config."
	fi
	;;
"braces")
	xmodmap $HOME/.xmodmap_braces
    if [[ $notify != 'hidden' ]] # not empty
		then
		notify-send -i /usr/share/icons/gnome/48x48/devices/keyboard.png "Braces set to primary."
	fi
	;;
"brackets")
	xmodmap $HOME/.xmodmap_sbrackets
    if [[ $notify != 'hidden' ]] # not empty
		then
		notify-send -i /usr/share/icons/gnome/48x48/devices/keyboard.png "Square Brackets set to primary."
	fi
	;;
"greek")
	xmodmap $HOME/.xmodmap_greek
    if [[ $notify != 'hidden' ]] # not empty
		then
		notify-send -i /usr/share/icons/gnome/48x48/devices/keyboard.png "Greek letters enabled."
	fi
	;;
"bash-completion")
	echo "$completion"
	;;
"--help"|"-h"|"help"|*)
	echo "Available options: help bash-completion setup braces brackets"
	exit
	;;
esac
