#!/bin/zsh

scripts=/home/ross/.scripts

location_log=/home/ross/.location

location=$1
state=$2

case $location in
"uni")
  (sleep 10; sudo -u ross $scripts/como unmount; sudo -u ross $scripts/como mount) &
  	echo "uni" > $location_log
  ;;
"home")
  (sleep 10; sudo -u ross $scripts/eris unmount; sudo -u ross $scripts/eris mount; sudo -u ross $scripts/backup) &
  echo "home" > $location_log
  ;;
"default" | "phone")
  echo $location > $location_log
  ;;
"refresh")
  $0 $(< $location_log )
  ;;
"status" | *)
	echo "At" $(cat $location_log)
  ;;
esac
