#!/bin/zsh

# based on using this specific fork, aka the ricing fork
# https://github.com/PandorasFox/i3lock-color

B='#00000000'  # blank
D='#ddddddff'  # light grey default
T='#000000ff'  # black text
H='#57c7ffff'  # blue highlight
W='#990000ff'  # red wrong
Z='#00ff00ff'  # green test

# /home/ross/.scripts/monitor auto

i3lock \
--insidevercolor=$D   \
--ringvercolor=$D     \
\
--insidewrongcolor=$W \
--ringwrongcolor=$W   \
\
--insidecolor=$D      \
--ringcolor=$D        \
--linecolor=$D        \
--separatorcolor=$D   \
--keyhlcolor=$H       \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--bshlcolor=$Z        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="Locked" \
#--datestr="%d %b - D%j W%V" \
# --keylayout 2         \

# /home/ross/.scripts/monitor auto
