#!/bin/sh
## make an image ready for the lockscreen


wallpaper=$1
filename=`basename $wallpaper`
sansext="${filename%.*}"
SIZE=$(/home/ross/.scripts/screens resolution)
lock=/home/ross/pictures/Wallpaper/lock_grey.png
output=/home/ross/pictures/Wallpaper/locked/$sansext.lock.png
locked_wallpaper=/home/ross/pictures/Wallpaper/current_lock

rm $locked_wallpaper
ln -s $output $locked_wallpaper

if [ ! -e "$output" ]
then
  ## kill any already running convert processes, as there can be race conditions
  pkill convert
  ## The square brackets after the input forces an immediate resize. This speeds up subsequent operations, and makes the lock a standard size.
  convert $wallpaper"[$SIZE]" $lock -gravity center -composite -matte -format png $output
fi
