#!/bin/zsh

# based on using this specific fork, aka the ricing fork
# https://github.com/PandorasFox/i3lock-color

BLANK='#00000000'  # blank
GREY='#dddddd'  # light grey default
TEXT='#000000ff'  # black text
HIGHLIGHT='#57c7ffff'  # blue highlight
WRONG='#990000ff'  # red wrong
Z='#00ff00ff'  # green test

i3lock \
--insidever-color=$GREY     \
--ringver-color=$GREY   \
\
--insidewrong-color=$GREY   \
--ringwrong-color=$WRONG     \
\
--inside-color=$GREY        \
--ring-color=$GREY        \
--line-color=$GREY          \
--separator-color=$BLANK   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$HIGHLIGHT         \
--bshl-color=$HIGHLIGHT          \
\
--screen 1                   \
--blur 5                     \
--clock                      \
--indicator                  \
--radius=70		\
--time-str="%H:%M:%S"        \
--time-size=24        \
--date-str="%A, %m %Y"       \
--verif-size=24
#--keylayout 0                \