#!/bin/zsh

image="/tmp/lock_screen.png"
lock="/home/ross/pictures/Wallpaper/lock_grey.png"

## Take a screenshot
#scrot $image

# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
#BLURTYPE="0x5" # 7.52s
#BLURTYPE="0x2" # 4.39s
#BLURTYPE="5x3" # 3.80s
BLURTYPE="2x8" # 2.90s
#BLURTYPE="2x3" # 2.92s
# convert $image -level 0%,100%,0.6 -blur $BLURTYPE -font Liberation-Sans -pointsize 26 -fill white -gravity center -annotate +0+200 'Type password to unlock' - | composite -gravity center $lock - $image

## Blur the image
#convert $image -scale 10% -scale 1000% $image

## Compose with lock screen icon
#[[ -f $lock ]] && convert $image $lock -gravity center -composite -matte $image

#i3lock --textcolor=00000000 --insidecolor=00000000 --ringcolor=008800ff --linecolor=00000000 --keyhlcolor=00ff00ff --ringvercolor=cccc00ff --insidevercolor=cccc0000 --ringwrongcolor=ff0000ff --insidewrongcolor=ff000000 -i $image
i3lock -i $image -z
