#!/bin/zsh
#set -x
export DISPLAY=:0

# sleep 2
USER="ross"
sc="/home/ross/.scripts/screens"
hdmi_status="$(</sys/class/drm/card0-HDMI-A-1/status)"
#hdmi_status=`su $USER -c "$sc status"`

#if [[ $hdmi_status == "single" ]]; then
if [[ $hdmi_status == "disconnected" ]]; then
    [[ $(pgrep X) > 0 ]] && su $USER -c "$sc off"
else
    [[ $(pgrep X) > 0 ]] && su $USER -c "$sc on"
fi

exit 0
