#!/bin/sh
#
# This script toggles the extended monitor outputs if something is connected
#

completion='compctl -k "(help bash-completion mirror off toggle status auto resolution height width)" monitor'

# laptop monitor
DEFAULT_OUTPUT='eDP-1'
SEC_OUTPUT='HDMI-1'
#string to execute at the end
EXECUTE="xrandr --output $DEFAULT_OUTPUT --primary --auto "

# WALLPAPER='echo wallpaper >> /tmp/screens.log'
WALLPAPER='/home/ross/.scripts/wallpaper random'
#WALLPAPER='/home/ross/.scripts/wallpaper refresh'

WACOM='/home/ross/.scripts/wacom laptop'

function resolution(){
	echo `xrandr --current | sed -n 's/.* current \([0-9]*\) x \([0-9]*\).*/\1x\2/p'`
}
function width(){
	echo `xrandr --current | sed -n 's/.* current \([0-9]*\) x \([0-9]*\).*/\1/p'`
}
function height(){
	echo `xrandr --current | sed -n 's/.* current \([0-9]*\) x \([0-9]*\).*/\2/p'`
}

function side_by_side(){
	EXECUTE+="--output $SEC_OUTPUT --auto --left-of $DEFAULT_OUTPUT "
	$EXECUTE
	$WALLPAPER
	$WACOM
}
function mirror(){
	EXECUTE+="--output $SEC_OUTPUT --auto --same-as $DEFAULT_OUTPUT "
	$EXECUTE
	$WALLPAPER
	$WACOM
}
function off(){
	EXECUTE+="--output $SEC_OUTPUT --off "
	$EXECUTE
	$WALLPAPER
}

case $1 in
"--help"|"-h"|"help")
	echo "Available options: help; status; on, mirror, off, toggle, auto"
	exit
	;;

"bash-completion")
	echo "$completion"
	;;

"on")
	side_by_side
	;;
"mirror")
	mirror
	;;
"off")
	off
	;;
"toggle")
	if (xrandr --current | grep "$SEC_OUTPUT\ connected\ (" -q) # is disabled
		then
		side_by_side
		# echo "side-by-side"
	else
		off
		# echo "disabled"
	fi
	;;
"status")
	status=$(xrandr --current)
	if (echo $status | grep -q "$SEC_OUTPUT\ connected") # is connected
		then if ((echo $status | grep "$SEC_OUTPUT\ connected\ (" -q) || (echo $status | grep "$SEC_OUTPUT\ connected\ primary\ (" -q))
			then
			echo "disabled"
			else
			echo "dual"
		fi
	else
		echo "single"
	fi
	;;
"resolution")
	resolution
	;;
"height")
	height
	;;
"width")
	width
	;;
"auto" | *)
	if (xrandr  --current | grep -q "$SEC_OUTPUT\ connected") # is connected
		then
		side_by_side
	else # make sure disconnected outputs are off
		off
	fi
	;;
esac
