#!/bin/zsh

FILE=`basename "$1"`
MOUNTPOINT="/media/ross/$FILE"
#PWD=`pwd`

#echo "$1 -- $FILE -- $MOUNTPOINT -- $PWD">> /home/ross/test

#fuseiso -p "$1" "$MOUNTPOINT" >> home/ross/test
fuseiso -p "$1" "$MOUNTPOINT"
