#!/bin/sh

case $1 in
   "play")
    #    key="space"
        cmd="PlayPause"
       icon_name="/usr/share/icons/gnome/48x48/actions/media-playback-start.png"
       ;;
   "next")
    #    key="Right"
       cmd="Next"
       icon_name="/usr/share/icons/gnome/48x48/actions/media-skip-forward.png"
       ;;
   "prev")
    #    key="Left"
       cmd="Previous"
       icon_name="/usr/share/icons/gnome/48x48/actions/media-skip-forward-rtl.png"
       ;;
   *)
       echo "Usage: $0 play|next|prev"
       exit 1
        ;;
esac

# xdotool key --window $(xdotool search --name "Spotify"|head -n1) $key

dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.$cmd

notify-send -i $icon_name -t 1000 "Spotify: $1"

exit 0
