#!/bin/sh

case $1 in
   "play")
       key="space"
       icon_name="/usr/share/icons/gnome/48x48/actions/media-playback-start.png"
       ;;
   "next")
       key="Right"
       icon_name="/usr/share/icons/gnome/48x48/actions/media-skip-forward.png"
       ;;
   "prev")
       key="Left"
       icon_name="/usr/share/icons/gnome/48x48/actions/media-skip-forward-rtl.png"
       ;;
   *)
       echo "Usage: $0 play|next|prev"
       exit 1
        ;;
esac

xdotool key --window $(xdotool search --name "Rdio"|head -n1) $key

notify-send -i $icon_name -t 1000 "Rdio: $1"

exit 0
