#!/bin/zsh

arg=$3
synctex="/home/ross/.scripts/zathura-synctex"

pdf_file=$(grep -o '^[^#]*' <<< "$arg")
tex_file=$(sed -n -e 's_.*src:[0-9]*\(.*\)_\1_p' <<< "$arg")
line_num=$(sed -n -e 's_.*src:\([0-9]*\).*_\1_p' <<< "$arg")

#echo "pdf: " $pdf_file >> /home/ross/log
#echo "tex: " $tex_file >> /home/ross/log
#echo "line: " $line_num >> /home/ross/log

#zathura-synctex "$line_num:1:$tex_file" "$pdf_file"
$synctex "$line_num:1:$tex_file" "$pdf_file"
