#!/bin/sh
config_dir=/etc/tinyproxy/
config_file=/etc/tinyproxy/tinyproxy.conf
log_file=/home/ross/proxyswitcher.log
DEBUG=no

function clear_config {
if [ -e $config_file ]; then
   rm $config_file
fi
}

function tinyproxyreload {
	pkill tinyproxy
	sleep 2
	tinyproxy
}

function proxy_uni {
  ln -s "$config_dir"tinyproxy_uni.conf $config_file
  tinyproxyreload
  [ "$DEBUG" == "yes" ] && echo "tinyproxy reloaded with uni profile" >> $log_file
  sudo -u ross notify-send -i info --hint int:transient:1 "Uni proxy activated"
}

function proxy_home {
  ln -s "$config_dir"tinyproxy_home.conf $config_file
  tinyproxyreload
  [ "$DEBUG" == "yes" ] && echo "tinyproxy reloaded with home profile" >> $log_file
  DISPLAY=:0 notify-send -i info --hint int:transient:1 "Home proxy activated"
}

function proxy_off {
  ln -s "$config_dir"tinyproxy_off.conf $config_file
  tinyproxyreload
  [ "$DEBUG" == "yes" ] && echo "tinyproxy reloaded with off profile" >> $log_file
  sudo -u ross notify-send -i info --hint int:transient:1 "Proxy de-activated" 
}

function proxy_check {
  echo "\""`ls -al /etc/tinyproxy/tinyproxy.conf | grep -o '_\w*\.conf' | sed -e "s/_//" -e "s/\.conf//"`"\" profile active"
}

case $1 in
	"help")
		echo "Usage: $0 [uni|home|default|status|help]"
		;;
  "uni")
    clear_config
    proxy_uni
    ;;
  "home")
    clear_config
		proxy_home
		;;
	"default")
    clear_config
    proxy_off
    ;;
  "status" | *)
    proxy_check
    ;;
esac
