#!/bin/sh
#
# This script toggles the extended monitor outputs if something is connected
#


completion='compctl -k "(help bash-completion mirror off toggle status auto)" screens'


# laptop monitor
DEFAULT_OUTPUT='eDP1'
SEC_OUTPUT='HDMI1'
#string to execute at the end
EXECUTE="xrandr --output $DEFAULT_OUTPUT --auto "

WALLPAPER='/home/ross/.scripts/wallpaper refresh'

function side_by_side(){
	EXECUTE+="--output $SEC_OUTPUT --auto --right-of $DEFAULT_OUTPUT --primary "
	$EXECUTE
	$WALLPAPER
}
function mirror(){
	EXECUTE+="--output $SEC_OUTPUT --auto --same-as $DEFAULT_OUTPUT "
	$EXECUTE
	$WALLPAPER
}
function off(){
	EXECUTE+="--primary --output $SEC_OUTPUT --off "
	$EXECUTE
	$WALLPAPER
}

case $1 in
"--help"|"-h"|"help")
	echo "Available options: help; status; on, mirror, off, toggle, auto"
	exit
	;;

"bash-completion")
	echo "$completion"
	;;

"on")
	side_by_side
	;;
"mirror")
	mirror
	;;
"off")
	off
	;;
"toggle")
	if (xrandr --current | grep "$SEC_OUTPUT\ connected\ (" -q) # is disabled
		then
		side_by_side
		# echo "side-by-side"
	else
		off
		# echo "disabled"
	fi
	;;
"status")
	status=$(xrandr --current)
	if (echo $status | grep -q "$SEC_OUTPUT\ connected") # is connected
		then if (echo $status | grep "$SEC_OUTPUT\ connected\ (" -q) # is disabled
			then
			echo "disabled"
			else
			echo "dual"
		fi
	else
		echo "single"
	fi
	;;
"auto" | *)
	if (xrandr  --current | grep -q "$SEC_OUTPUT\ connected") # is connected
		then
		side_by_side
	else # make sure disconnected outputs are off
		off
	fi
	;;
esac
