#!/bin/zsh

## change to the right directory
cd /media/seagate2/tv

## rename everything properly
tvnamer --config=/home/ross/.config/tvnamer/tvnamer.json --batch --recursive .

## clean up crap to another folder for review (I'm too chicken to delete it outright until well tested)
## The (N) suppresses the error on a failed glob match
## The ~ says to do glob expansion on that variable
folders=./*/*/(N)
echo $~folders
## [[ ! -z $~folders ]] &&  mv $~folders ../crap/
## [[ ! -z $~folders ]] &&  rm -r $~folders

## copy this whole directory onto the backup pool, skipping any files that are already there 
## (in effect we are making the pool into a superset of this)
target=/media/btrfs3-new/stuff/tv/
rsync -av ./ $target
