#!/bin/sh

volume=$1
muted=$2
headphones=$3

if [ "$volume" = "0" ]; then
    # icon_name="notification-audio-volume-off"
    icon_name="/usr/share/icons/Adwaita/48x48/status/audio-volume-low.png"
else
    if [ "$volume" -lt "33" ]; then
        # icon_name="notification-audio-volume-low"
        icon_name="/usr/share/icons/Adwaita/48x48/status/audio-volume-low.png"
    else
        if [ "$volume" -lt "67" ]; then
            # icon_name="notification-audio-volume-medium"
            icon_name="/usr/share/icons/Adwaita/48x48/status/audio-volume-medium.png"
        else
            # icon_name="notification-audio-volume-high"
            icon_name="/usr/share/icons/Adwaita/48x48/status/audio-volume-high.png"
        fi
    fi
fi

if [[ "$headphones" = "on" ]]; then
    # icon_name="/usr/share/icons/gnome/48x48/devices/audio-headphones.png"
    # icon_name="/usr/share/icons/gnome/scalable/devices/audio-headphones-symbolic.svg"
    icon_name="/usr/share/icons/Adwaita/48x48/devices/audio-headphones.png"
fi

echo $muted
if [[ "$muted" = "yes" ]]; then
    # icon_name="notification-audio-volume-muted"
    icon_name="/usr/share/icons/Adwaita/48x48/status/audio-volume-muted.png"
fi



# echo $icon_name

notify-send " " -i $icon_name -h int:value:$volume -h string:synchronous:volume

# volnoti-show $volume
