#!/bin/sh

completion='compctl -k "(up down set mute unmute toggle is_muted is_headphone is_speaker level show help)" volume'

function get_level {
  pamixer --get-volume
}

function is_muted {
  pamixer --get-mute
}

function is_headphone {
  sinks=$(pactl list sinks)
  if echo $sinks | grep -q "Active Port: analog-output-headphones"; then echo "true"; else echo "false"; fi
}

function is_speaker {
  sinks=$(pactl list sinks)
  if echo $sinks | grep -q "Active Port: analog-output-speaker"; then echo "true"; else echo "false"; fi
}

function show {
  echo "showing"
  /home/ross/.scripts/volume_show `get_level` `is_muted` `is_headphone` &
}

case $1 in
"up")
  pamixer --increase 5
  show
  ;;
"down")
  pamixer --decrease 5
  show
  ;;
"set")
  pamixer --set-volume $2
  show
  ;;
"mute")
  pamixer --mute
  show
  ;;
"unmute")
  pamixer --unmute
  show
  ;;
"toggle")
  pamixer --toggle-mute
  show
  ;;

"is_muted")
  is_muted
  ;;
"is_headphone")
  is_headphone
  ;;
"is_speaker")
  is_speaker
  ;;

"level")
  get_level
  ;;
"show")
  show
  ;;

"bash-completion")
	echo "$completion"
	;;
"help"|*)
  echo "Basically a wrapper on pulseaudio-ctl that also shows a volume notification"
  echo "Usage: up|down|mute|unmute|toggle|is_muted|is_headphone|is_speaker|level"
  echo "Volume: " `get_level`"%"
  ;;
esac

exit 1
