#!/bin/sh

completion='compctl -k "(up down mute unmute toggle is_muted is_headphone is_speaker level show help)" volume'

function get_level {
  pulseaudio-ctl full-status | grep -P -o "[0-9]*"
}

sinks=$(pactl list sinks)
function is_muted {
  if echo $sinks | grep -A6 -m1 "alsa_output.pci-0000_00_1b.0.analog-stereo" | grep -q "Mute: yes"; then echo "yes"; else echo "no"; fi
}

function is_headphone {
  if echo $sinks | grep -q "Active Port: analog-output-headphones"; then echo "yes"; else echo "no"; fi
}

function is_speaker {
  if echo $sinks | grep -q "Active Port: analog-output-speaker"; then echo "yes"; else echo "no"; fi
}

function show {
  /home/ross/.scripts/volume_show `get_level` `is_muted` `is_headphone` &
}

case $1 in
"up")
  pulseaudio-ctl up
  show
  ;;
"down")
  pulseaudio-ctl down
  show
  ;;
"mute")
  pactl -- set-sink-mute 1
  show
  ;;
"unmute")
  pactl -- set-sink-mute 0
  show
  ;;
"toggle")
  pulseaudio-ctl mute
  show
  ;;

"is_muted")
  is_muted
  ;;
"is_headphone")
  is_headphone
  ;;
"is_speaker")
  is_speaker
  ;;

"level")
  get_level
  ;;
"show")
  show
  ;;

"bash-completion")
	echo "$completion"
	;;
"help"|*)
  echo "Basically a wrapper on pulseaudio-ctl that also shows a volume notification"
  echo "Usage: up|down|mute|unmute|toggle|is_muted|is_headphone|is_speaker|level"
  echo "Volume: " `get_level`"%"
  ;;
esac

exit 1
