#!/bin/sh

function get_level {
  pulseaudio-ctl | grep -P "(?=Volume level).*" | grep -P -o "[0-9]*(?= %)"
  # pactl list sinks | grep -A15 "alsa_output.pci-0000_00_1b.0.analog-stereo" | grep -P -o -m 1 "[0-9]*(?=\\%)" | grep -m 1 ".*"
}

function muted {
  if [[ `pactl list sinks | grep -A15 "alsa_output.pci-0000_00_1b.0.analog-stereo"` =~ "Mute: yes" ]]; then echo "yes"; else echo "no"; fi
}

function mute_status {
  if [[ `pactl list sinks | grep -A15 "alsa_output.pci-0000_00_1b.0.analog-stereo"` =~ "Mute: yes" ]]; then echo "yes"; fi
}

function headphone {
  if [[ `pactl list sinks` =~ "Active Port: analog-output-headphones" ]]; then echo "yes"; else echo "no"; fi
}

function speaker {
if [[ `pactl list sinks` =~ "Active Port: analog-output-speaker" ]]; then echo "yes"; else echo "no"; fi
}

# function headphone_switch {
#   if [[ `pactl list sinks` =~ "Active Port: analog-output-headphones" ]]; then
#     pactl set-sink-port alsa_output.pci-0000_00_1b.0.analog-stereo analog-output-headphones
#   else
#     pactl set-sink-port alsa_output.pci-0000_00_1b.0.analog-stereo analog-output-speaker
#   fi
#   show
# }

function show {
  # echo `get_level` `muted`
  /home/ross/.local/bin/volume-show `get_level` `muted` `headphone`
}

case $1 in
"up")
  pulseaudio-ctl up
  show
  ;;
"down")
  pulseaudio-ctl down
  # pactl -- set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo -5%
  show
  ;;
"mute")
  # pactl -- set-sink-mute 1
  show
  ;;
"unmute")
  # pactl -- set-sink-mute 0
  show
  ;;
"toggle")
  pulseaudio-ctl mute
  # amixer -q sset Master toggle
  show
  ;;
# "headphone_on")
#   pactl set-sink-port alsa_output.pci-0000_00_1b.0.analog-stereo analog-output-headphones
#   show
#   ;;
# "headphone_off")
#   pactl set-sink-port alsa_output.pci-0000_00_1b.0.analog-stereo analog-output-speaker
#   show
#   ;;
# "headphone_switch")
#   headphone_switch
#   ;;
# "headphone_acpi")
#   headphone_acpi $2
#   ;;
"muted")
  muted
  ;;
"mute_status")
  mute_status
  ;;
"headphone")
  headphone
  ;;
"speaker")
  speaker
  ;;
"level")
  get_level
  ;;
"show")
  show
  ;;
"help"|*)
  echo "Usage: up|down|mute|unmute|toggle|muted|level"
  echo "Volume: " `$0 level`
  ;;
esac

exit 1
