#!/bin/sh

volume=$1
muted=$2
headphones=$3

# echo $volume
# echo $muted
# echo $headphones

if [ "$volume" = "0" ]; then
    icon_name="/usr/share/icons/elementary/status/48/audio-volume-low-symbolic.svg"
elif [ "$volume" -lt "33" ]; then
    icon_name="/usr/share/icons/elementary/status/48/audio-volume-low-symbolic.svg"
elif [ "$volume" -lt "67" ]; then
    icon_name="/usr/share/icons/elementary/status/48/audio-volume-medium-symbolic.svg"
else
    icon_name="/usr/share/icons/elementary/status/48/audio-volume-high-symbolic.svg"
fi

if [[ "$headphones" = "yes" ]]; then
    icon_name="/usr/share/icons/gnome/scalable/devices/audio-headphones-symbolic.svg"
fi

if [[ "$muted" = "yes" ]]; then
    icon_name="/usr/share/icons/elementary/status/48/audio-volume-muted-symbolic.svg"
fi



# echo $icon_name

notify-send " " -i $icon_name -h int:value:$volume -h string:synchronous:volume

