#!/bin/sh

completion='compctl -k "(help bash-completion start stop)" vpn'

case $1 in
"help")
	echo "Available options: help; start; stop; bash-completion"
	;;

"bash-completion")
	echo $completion
	;;

"stop")
	nordvpn disconnect
	# sudo nordvpn stop
	# sleep 2
    # route
	;;

"start")
	nordvpn connect France
	# sudo nordvpn start $(sudo nordvpn list de | shuf -n 1)
	# sleep 2
    # route
	;;

"*")
	nordvpn status
	# sudo nordvpn $*
	# sleep 2
    # route
	;;
esac
