#!/bin/zsh

COMPLETION='compctl -k "(help bash-completion current refresh random reddit save-reddit)" wallpaper'

WALLPAPERS="/home/ross/pictures/Wallpaper/"
SUBREDDIT_URL="https://imgur.com/r/skyporn+weatherporn"

CURRENT_LN=$WALLPAPERS"current"
DIR=$WALLPAPERS"Single/"
REDDIT=$WALLPAPERS"reddit.jpg"

function count_screens() {
	STATUS=$(/home/ross/.scripts/screens status)
	if [ $STATUS = 'dual' ];
	then
	DIR="/home/ross/pictures/Wallpaper/Dual"
	else
	DIR="/home/ross/pictures/Wallpaper/Single"
fi
}

function bg_set_random() {
	count_screens

	CHOICE=$(find $DIR -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z)

	set_wallpaper $CHOICE
}

function bg_refresh() {
	REALPATH=$(realpath $CURRENT_LN)

	set_wallpaper $REALPATH
}

function bg_fetch_reddit() {
	ID="$(wget -q $SUBREDDIT_URL -O - | grep '"post"' | grep class | cut -d\" -f 2 | head -1)"
	echo "Downloading $ID.jpg"
	wget -q "http://i.imgur.com/$ID.jpg" -O $REDDIT

	set_wallpaper $REDDIT
}

function bg_save_reddit() {
	NEW_FILE='reddit_'$(date +%F-%H%M%S)'.jpg'
	cp $REDDIT $NEW_FILE
}

function set_wallpaper() {
	nitrogen --set-scaled $1
	rm $CURRENT_LN
	ln -s $1 $CURRENT_LN

#	/home/ross/.scripts/prep_lock_screen $1
}

case $1 in
"--help"|"-h"|"help")
	echo "Available options: help, bash-completion, current, refresh, random, reddit."
	echo "Current return the true path of the current wallpaper. This is what returns if no arguments are passed."
	echo "Refresh puts the most recent wallpaper as the wallpaper."
	exit
	;;

"bash-completion")
	echo "$COMPLETION"
	;;

"" | "current")
	realpath $CURRENT_LN
	;;

"refresh")
	bg_refresh
	;;

"random")
	bg_set_random
	;;

"reddit")
	bg_fetch_reddit
	;;

"save-reddit")
	bg_save_reddit
	;;

*)
	set_wallpaper $*
	;;
esac
