#!/bin/zsh

WALLPAPERS="/home/ross/pictures/Wallpaper/"

function bg_set_random_dualspan() {
	DIR="/home/ross/pictures/Wallpaper/Dual"
	CHOICE=$(find $DIR -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z)
	nitrogen --set-scaled $CHOICE
}
function bg_set_random_dualduo() {
	DIR="/home/ross/pictures/Wallpaper/Single"
	CHOICE=$(find $DIR -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z)
	nitrogen --head=0 --set-scaled $CHOICE

	CHOICE=$(find $DIR -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z)
	nitrogen --head=1 --set-scaled $CHOICE
}
function bg_set_random_single() {
	DIR="/home/ross/pictures/Wallpaper/Single"
	CHOICE=$(find $DIR -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z)
	nitrogen --set-scaled $CHOICE
}

function bg_set_random() {
	STATUS=$(/home/ross/.scripts/monitor status)
	if [ $STATUS = 'dual' ];
	then
#		bg_set_random_dualspan
		bg_set_random_dualduo
	else
		bg_set_random_single
	fi
}

bg_set_random
