#!/bin/zsh

cd ~/.xmonad/
stack install

success=$?

if [[ $success -eq 0 ]]; then
  notify-send -i /usr/share/icons/gnome/48x48/devices/video-display.png "Xmonad Compiled Successfully"
else
  notify-send -t 5000 -i /usr/share/icons/gnome/48x48/devices/video-display.png "Xmonad failed to compile. See log."
fi
